name: Build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

  check-syntax:
    name: Check code syntax
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load composer cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Check code syntax
      run: composer cs:check

  test-coverage:
    name: Test and upload artifacts
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Load composer cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Run test suite w/ coverage
      run: composer test:coverage
  
    - name: Upload html coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: build/html
        
    - name: Upload html coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: build/html

    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        name: Code coverage
        token: 07f39e06-24a4-41d1-8208-8599cb68fa16
        directory: build
        flags: unit
        fail_ci_if_error: true
